### ISSUE TITLE
Add benchmark compare with Tile38?

### ISSUE THREAD

**Issue by ringsaturn** [tair-opensource/TairGis#1]
[Tile38](https://github.com/tidwall/tile38) a Redis compatible database with many Geo feature support, I’m wondering performance differences between TairGis and Tile38.

**Comment by yangbodong22011** [comment]
Sorry, no plans at the moment, TairGis depends on [redis-gis](https://github.com/tidwall/redis-gis), which is also created by [tidwall](https://github.com/tidwall). We have not done special optimization for performance, only modified some algorithms, such as introducing W. Randolph Franklin's [algorithm](https://wrfranklin.org/Research/Short_Notes/pnpoly.html) to determine [whether a point is inside a polygon](https://github.com/tair-opensource/TairGis/blob/main/src/spatial/polyraycast.c#L156).

TairGis is mainly convenient for users to directly load GIS Module on Redis.

**Comment by ringsaturn** [comment]
Thanks.
